spring:
#    datasource:
#        url: jdbc:h2:mem:testdb
#        driver-class-name: org.h2.Driver
#        username: sa
#        password:
#    jpa:
#        database-platform: org.hibernate.dialect.H2Dialect
#        hibernate:
#            ddl-auto: none
#    h2:
#        console:
#            enabled: true

    jpa:
        database: POSTGRESQL
        hibernate.ddl-auto: none
        show-sql: true
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5433/hockey_db
        username: root
        password: root
    liquibase:
        change-log: classpath:/config/liquibase/master.xml
    sql:
        init:
            platform: postgres

